import React from "react";

export default function Page() {
  return (
    <main className="max-w-2xl mx-auto px-4 py-8">
      {/* Badge */}
      <div className="mb-4">
        <span className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-gray-100 text-sm text-gray-700">
          <span className="w-3 h-3 rounded-full bg-yellow-300 inline-block" />
          Member-only story
        </span>
      </div>

      {/* Title + Subtitle */}
      <header className="mb-6">
        <h1 className="text-4xl sm:text-5xl font-extrabold leading-tight mb-4">
          The Future of Decentralized Publishing
        </h1>
        <p className="text-lg text-gray-600 mb-6">
          Exploring how blockchain technology is revolutionizing content monetization
        </p>

        {/* Meta + Author Row */}
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-3">
              <img
                src="/avatar-3d.jpg"
                alt="Sarah Chen"
                className="w-11 h-11 rounded-full object-cover"
              />
              <div>
                <div className="font-medium">Sarah Chen</div>
                <div className="text-sm text-gray-500">9 min read · Apr 30, 2025</div>
              </div>
            </div>
          </div>

          <button
            className="ml-4 bg-orange-400 text-white px-4 py-2 rounded-2xl font-medium shadow-sm"
            type="button"
            onClick={() => window.alert("Follow clicked")}
          >
            Follow
          </button>
        </div>
      </header>

      {/* Cover image */}
      <figure className="mb-4 rounded-2xl overflow-hidden shadow">
        <img src="/featured-nft.jpg" alt="Cover" className="w-full h-64 object-cover" />
        <figcaption className="text-center text-sm text-gray-500 p-3">
          Generated by the author with AI.
        </figcaption>
      </figure>

      {/* Article content (secciones resumidas) */}
      <article className="prose prose-neutral max-w-none mb-8">
        <h2>The Current Challenge</h2>
        <p>
          Traditional publishing platforms operate on centralized models where intermediaries control distribution and monetization of content. This creates problems for creators...
        </p>

        <h2>Enter Blockchain Technology</h2>
        <p>
          Blockchain offers a paradigm shift: a decentralized infrastructure where creators can publish directly to their audience without intermediaries...
        </p>

        <h2>Real-World Applications</h2>
        <p>
          Several platforms are already pioneering this space. Mirror.xyz allows writers to publish on-chain and crowdfund through NFT sales...
        </p>

        <h2>The Path Forward</h2>
        <p>
          The future of publishing will likely be hybrid: combining the best aspects of traditional platforms with the empowerment blockchain provides...
        </p>
      </article>

      {/* Actions row */}
      <div className="flex items-center justify-between text-gray-600 mb-8">
        <div className="flex items-center gap-6">
          <button className="flex items-center gap-2" aria-label="like">
            <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none"><path d="M12 21s-7-4.35-9-7.5C1.5 9.75 4 6 7 6c1.8 0 2.8 1 3.5 1.9C11.2 7 12.2 6 14 6c3 0 5.5 3.75 4 7.5-2 3.15-9 7.5-9 7.5z" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/></svg>
            <span>245</span>
          </button>

          <button className="flex items-center gap-2" aria-label="comments">
            <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none"><path d="M21 15a2 2 0 0 1-2 2H8l-5 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/></svg>
            <span>32</span>
          </button>
        </div>

        <div className="flex items-center gap-4">
          <button aria-label="bookmark" className="p-2 rounded-lg hover:bg-gray-100">
            <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none"><path d="M6 2h12v20l-6-4-6 4V2z" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/></svg>
          </button>
          <button aria-label="share" className="p-2 rounded-lg hover:bg-gray-100" onClick={() => navigator.share?.({ title: 'Article', url: window.location.href })}>
            <svg className="w-5 h-5" viewBox="0 0 24 24" fill="none"><path d="M4 12v7a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-7" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/><path d="M12 3v14" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/><path d="M8 7l4-4 4 4" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round"/></svg>
          </button>
        </div>
      </div>

      {/* Author card */}
      <aside className="border rounded-2xl p-4 bg-white shadow-sm">
        <div className="flex items-start gap-4">
          <img src="/avatar-3d.jpg" alt="Sarah Chen" className="w-16 h-16 rounded-full object-cover" />
          <div className="flex-1">
            <div className="font-bold">Sarah Chen</div>
            <div className="text-sm text-gray-600 mb-3">Tech writer exploring the intersection of blockchain, AI, and creativity. Former engineer turned storyteller.</div>
            <button className="bg-white border border-gray-200 text-gray-800 px-4 py-2 rounded-full shadow-sm">Follow</button>
          </div>
        </div>
      </aside>
    </main>
  );
}
